# Site settings
title: wanglinzhizhi's blog
email: wanglinzhizhi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  万有引力的作用下，每个人的时间是相对的
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: wanglinzhizhi
github_username:  wagnlinzh

# Build settings
markdown: kramdown
